server:
  port: 18080

name: woogaris

spring:
  application:
    name: cloud-movie-front

management:
  security:
    enabled: false

rest:
  address: http://localhost:8090

---

server:
  port: 18080

name: woogaris-default

spring:
  profiles: default
  application:
    name: cloud-movie-front

management:
  security:
    enabled: false

---

server:
  port: 18080

name: woogaris-k8s

spring:
  profiles: k8s
  application:
    name: cloud-movie-front

management:
  security:
    enabled: false
